"""crear_tablas_inventario

Revision ID: 277859e4608a
Revises: 
Create Date: 2026-04-14 11:53:14.531799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '277859e4608a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('negocios',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('propietario', sa.String(length=200), nullable=False),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('moneda', sa.String(length=10), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('almacenes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('negocio_id', sa.String(length=36), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('ubicacion', sa.String(length=200), nullable=True),
    sa.Column('es_principal', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['negocio_id'], ['negocios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categorias',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('negocio_id', sa.String(length=36), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('icono', sa.String(length=50), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['negocio_id'], ['negocios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proveedores',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('negocio_id', sa.String(length=36), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['negocio_id'], ['negocios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('productos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('negocio_id', sa.String(length=36), nullable=False),
    sa.Column('categoria_id', sa.String(length=36), nullable=True),
    sa.Column('proveedor_id', sa.String(length=36), nullable=True),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('codigo_barras', sa.String(length=100), nullable=True),
    sa.Column('unidad_medida', sa.String(length=30), nullable=False),
    sa.Column('tiene_variantes', sa.Boolean(), nullable=False),
    sa.Column('es_servicio', sa.Boolean(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['negocio_id'], ['negocios.id'], ),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('variantes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('producto_id', sa.String(length=36), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('atributos', sa.JSON(), nullable=True),
    sa.Column('precio_venta', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('precio_costo', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('foto_url', sa.String(length=500), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movimientos_stock',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('variante_id', sa.String(length=36), nullable=False),
    sa.Column('almacen_id', sa.String(length=36), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('costo_unitario', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('referencia_id', sa.String(length=100), nullable=True),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.Column('usuario_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['almacen_id'], ['almacenes.id'], ),
    sa.ForeignKeyConstraint(['variante_id'], ['variantes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('variante_id', sa.String(length=36), nullable=False),
    sa.Column('almacen_id', sa.String(length=36), nullable=False),
    sa.Column('cantidad_actual', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('cantidad_minima', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('cantidad_maxima', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('actualizado_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['almacen_id'], ['almacenes.id'], ),
    sa.ForeignKeyConstraint(['variante_id'], ['variantes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('variante_id', 'almacen_id', name='uq_stock_variante_almacen')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock')
    op.drop_table('movimientos_stock')
    op.drop_table('variantes')
    op.drop_table('productos')
    op.drop_table('proveedores')
    op.drop_table('categorias')
    op.drop_table('almacenes')
    op.drop_table('negocios')
    # ### end Alembic commands ###
